# Site settings
name: Rajat Singh
email: rajat94.singh@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Web Developer"
skills: "Java, Python, HTML, CSS, Reactjs, Angular, Nodejs, JavaScript, Rest, Git"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rajatsingh94/
  - title: Github
    url: https://github.com/rajatsingh94
  - title: twitter
    url: https://twitter.com/Rajat94_singh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
